version: "3.8"

services:
  db:
    image: postgres:13
    container_name: chat_db
    environment:
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=chatpass
      - POSTGRES_DB=chatdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - chatnet

  backend:
    build: ./backend
    container_name: chat_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://chatuser:chatpass@db/chatdb
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - FILES_MAX_MB=${FILES_MAX_MB}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge

volumes:
  postgres_data:
